#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI 

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



feh --bg-scale /home/rev/Resimler/wallpapers/Ekran\ görüntüsü\ 2021-07-06\ 22-10-00.png


bash ~/.config/polybar/launch.sh --blocks && compton




